# Generated by Django 4.1.4 on 2023-01-20 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locator', '0002_address_organizer_event_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(default='/images/default.jpg', upload_to='images/'),
        ),
    ]
