# Generated by Django 4.1.4 on 2023-01-20 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locator', '0003_search_alter_event_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='city',
            field=models.CharField(default='Berlin', max_length=100),
        ),
        migrations.AddField(
            model_name='address',
            name='cityCode',
            field=models.PositiveIntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='address',
            name='country',
            field=models.CharField(default='Germany', max_length=100),
        ),
        migrations.AddField(
            model_name='address',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='address', to='locator.event'),
        ),
        migrations.AddField(
            model_name='address',
            name='streetNr',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='event',
            name='color',
            field=models.CharField(choices=[('legacy', 'Legacy'), ('modern', 'Modern'), ('pioneer', 'Pioneer'), ('commander', 'Commander'), ('pauper', 'Pauper'), ('draft', 'Draft')], default='legacy', max_length=10),
        ),
        migrations.AddField(
            model_name='organizer',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organizer', to='locator.event'),
        ),
        migrations.AlterField(
            model_name='organizer',
            name='description',
            field=models.TextField(),
        ),
    ]
