# Generated by Django 4.1.4 on 2023-01-20 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locator', '0004_address_city_address_citycode_address_country_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='color',
            new_name='format',
        ),
        migrations.AddField(
            model_name='event',
            name='eintritt',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='event',
            name='maxTeilnehmer',
            field=models.PositiveIntegerField(default=24),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(default='Location and Date', max_length=200),
        ),
    ]
